[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"
  functions = "netlify/functions/backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/backend/server"
  status = 200
