[build]
  base = "frontend"
  functions = "netlify/functions/backend"
  command = "npm install --prefix netlify/functions/backend && npm run build"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/backend/server"
  status = 200
